version: '3'

services:
  postgres:
    image: postgres:13
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: chat
      POSTGRES_PASSWORD: 83355806
    ports:
      - "5432:5432"
    networks:
      - my-network

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-nestjs-app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 83355806
      POSTGRES_DATABASE: chat
    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network:
